### ISSUE TITLE
Update Requirements.txt

### ISSUE THREAD

**Issue by Bojak4616** [nmpiazza/LEACH-Exile#11]
Add the crypto library we will be using. (specify version if possible so I can download it too)

**Comment by nmpiazza** [comment]
Can do :)

Nicholas Piazza
Master’s Student Rochester Institute of Technology
B.S./M.S. Computing Security
Vice President of RIT's Competitive Cybersecurity Club (RC3)
Email: nmp5860@rit.edu
GitHub: https://github.com/nmpiazza
LinkedIn: https://linkedin.com/in/nicholasmpiazza/
RC3: https://rc3.club

**Comment by nmpiazza** [comment]
Our only dependencies are scapy and argparse.  This was updated in b7b642efa664c40023d4edf578c1d95818e61cd9
