### ISSUE TITLE
Implement Sink

### ISSUE THREAD

**Issue by nmpiazza** [nmpiazza/LEACH-Exile#6]
This node will function as the sink for the virtual LEACH network.  It will accept communications from the clusterheads in the network.  It will forward relevant traffic to an Intrusion Detection System.  It will act as the issuer of the exile notifications for the network.

**Comment by Bojak4616** [comment]
This should have the same port every time to make CH communication easier

**Comment by nmpiazza** [comment]
Agreed.  Let's reserve port 50,000 for the sink.

**Comment by Bojak4616** [comment]
To isolate network traffic, the virtual machine this will be tested on will have an extra networking card that Snort will be listening on.
